# Generated by Django 6.0.4 on 2026-05-13 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('booking', 'Booking Support'), ('driver_admin', 'Driver-Admin'), ('user_admin', 'User-Admin')], default='user_admin', max_length=20),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='myapp.trip'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='myapp.booking'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='myapp.driver'),
        ),
    ]
