# Generated by Django 6.0.4 on 2026-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bus_route_schedule_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pass_active',
            field=models.BooleanField(default=False),
        ),
    ]
